kind: Secret
apiVersion: v1
metadata:
  name: argocd-vault-plugin-credentials
type: Opaque
stringData:
  AVP_AUTH_TYPE: "approle"
  AVP_ROLE_ID: role_id
  AVP_SECRET_ID: secret_id
  AVP_K8S_ROLE: "argocd"
  AVP_TYPE: "vault"
  VAULT_ADDR: "https://vault-test.apps.okd-stg.payformance.io"
