kind: Secret
apiVersion: v1
metadata:
  name: argocd-vault-plugin-credentials
type: Opaque
stringData:
  AVP_AUTH_TYPE: "approle"
  AVP_ROLE_ID: a31bcc4e-b9db-aebc-7352-f6591a739a7e
  AVP_SECRET_ID: 30fc87e5-df0b-2917-baf8-771183df46ea
  AVP_K8S_ROLE: "argocd"
  AVP_TYPE: "vault"
  VAULT_ADDR: "https://vault-test.apps.okd-stg.payformance.io"